shipping:
  # number of generated shipping methods
  elementCount: 5
  # price range of each shipping method
  minPrice: 3.0
  maxPrice: 50.0

  # generate random custom attributes
  generatedAttributes:
    elementCount: 5
