/*
 *  Copyright (c) 2018, salesforce.com, inc.
 *  All rights reserved.
 *  SPDX-License-Identifier: BSD-3-Clause
 *  For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

package com.salesforce.comdagen.config

/**
 * Configuration for product bundles generated by CatalogGenerator.
 */
data class BundleProductConfiguration(
    val elementCount: Int = 20,

    /**
     * Minimum number of distinct products per bundle.
     */
    val minBundledProducts: Int = 2,

    /**
     * Maximum number of distinct products per bundle.
     */
    val maxBundledProducts: Int = 10,

    /**
     * Of each product SKU, how many items to put in a bundle?
     */
    val minQuantity: Int = 1,
    val maxQuantity: Int = 5
) {
    init {
        require(
            maxBundledProducts >= minBundledProducts,
            { "maxBundledProducts need to be greater equal minBundledProducts" })
    }
}