/*
 *  Copyright (c) 2018, salesforce.com, inc.
 *  All rights reserved.
 *  SPDX-License-Identifier: BSD-3-Clause
 *  For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

package com.salesforce.comdagen.config

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonRootName
import com.salesforce.comdagen.RenderConfig


/**
 * Configuration file for a library
 */
@JsonRootName("libraryConfig")
@JsonIgnoreProperties(ignoreUnknown = true)
data class LibraryConfiguration(
    override val initialSeed: Long = 1234,
    val generatedContentAssetCount: Int = 3,
    val folders: List<FolderConfiguration> = listOf(),
    @JsonProperty("folderDefaults")
    val defaultFolderConfigs: FolderConfiguration = FolderConfiguration(initialSeed, null, null, null, parent = null),
    val generatedFolderCount: Int = 6,
    @JsonProperty("generateSummaryContentAsset")
    val renderComdagenSummaryContentAsset: Boolean = true,
    @JsonProperty("contentAssetDefaults")
    val defaultContentAssetConfig: ContentConfiguration = ContentConfiguration(initialSeed, null, null),

    override val elementCount: Int = 1,
    override val outputFilePattern: String = "",
    override val outputDir: String = "libraries",
    override val templateName: String = "library.ftlx"
) : RenderConfig {

    /**
     * Returns the number of content assets that will be generated by this library and its custom libraries.
     * TODO: reimplement
     */
    fun totalContentAssetCount():Int = TODO()
//            /* Number of default generated content assets */ generatedContentAssetCount +
//            /* Number of content assets generated by custom libraries */ libraries.sumBy { it.generatedContentAssetCount }

    /**
     * Returns the number of folders that will be rendered in the template.
     */
    fun totalFolderCount(): Int = TODO() //{
//        val x =        /* Number of default generated folders */ generatedFolderCount +
//                /* Number of folders generated by custom libraries */ libraries.sumBy { it.generatedFolderCount }
//        return if (renderComdagenSummaryContentAsset) x + 1 else x
//    }

}